name: core-api
services:
- dockerfile_path: Dockerfile
  github:
    # TODO: change to main
    branch: ci/digitalocean-app-platform
    deploy_on_push: false
    repo: omshub/core-api
  http_port: 1927
  instance_count: 1
  instance_size_slug: basic-xxs
  name: core-api
  routes:
  - path: /
